packages:
  winget:
    - Microsoft.WindowsTerminal
    - Microsoft.PowerShell
    - ShareX.ShareX
    - Starship.Starship
    - OpenJS.NodeJS.LTS
  chocolatey:
    - fzf
    - ffmpeg
    - mingw
    - winfetch
    - nerd-fonts-JetBrainsMono
  python:
    - yt-dlp
    - thefuck
    - pygments
    - qrcode

links:
  - source: "./dotfiles/starship.toml"
    destination: "~/.config/starship.toml"

  - source: "./dotfiles/powershell.ps1"
    destination: "~/OneDrive/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

  - source: "./dotfiles/winfetch.ps1"
    destination: "~/.config/winfetch/config.ps1"
